version: '3'

services:
  amnet-front:
    build: .
    container_name: amnet-frontend
    restart: always
    expose:
      - '3000'
    labels:
      - "nginx-proxy.access=public"
    environment:
      - API_HOSTNAME=$API_HOSTNAME
      - API_PORT=$API_PORT
      - API_PROTOCOL=$API_PROTOCOL
      - NEXT_PUBLIC_API_HOST=$NEXT_PUBLIC_API_HOST
      - NEXT_PUBLIC_FAQ_STATE=$NEXT_PUBLIC_FAQ_STATE
      - NEXT_PUBLIC_GUEST_LOGIN=$NEXT_PUBLIC_GUEST_LOGIN
      - NEXT_PUBLIC_GUEST_PASSWORD=$NEXT_PUBLIC_GUEST_PASSWORD
      - NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID

      - VIRTUAL_HOST=amnet.fr
      - VIRTUAL_PORT=3000
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true