version: '3'

services:
  amnet-front:
    build: .
    environment:
      - API_HOSTNAME=$API_HOSTNAME
      - API_PORT=$API_PORT
      - API_PROTOCOL=$API_PROTOCOL
      - NEXT_PUBLIC_API_HOST=$NEXT_PUBLIC_API_HOST
      - NEXT_PUBLIC_FAQ_STATE=$NEXT_PUBLIC_FAQ_STATE
      - NEXT_PUBLIC_GUEST_LOGIN=$NEXT_PUBLIC_GUEST_LOGIN
      - NEXT_PUBLIC_GUEST_PASSWORD=$NEXT_PUBLIC_GUEST_PASSWORD
      - NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID